server:
  port: 8082
spring:
  application:
    name: inventory
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/inventory
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
