server:
  port: 8090

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/orders/**
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud-check/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
